### ISSUE TITLE
WagnerFischer doesn't handle asymmetric operation costs

### ISSUE THREAD

**Issue by mdempsky** [xrash/smetrics#5]
smetrics.WagnerFischer("abc", "xy", 2, 3, 5) returns 10, but it should return 13 (3 deletions at cost 3 + 2 insertions at cost 2).

**Comment by xrash** [comment]
Hey @mdempsky, thanks for your report!

You are right, the algorithm was incorrect. I believe I have fixed it now, can you check it out please?
